server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service-route
            uri: ${SERVICE_AUTH_URL:http://localhost:8081/api/auth-service}
            predicates:
              - Path=/api/auth-service/**